spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/h2-db
    password:
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
